apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: three-tier
  labels:
    role: api
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
        - name: api
          image: pavanvarikolu/prescriptobackend:1.0
          imagePullPolicy: Always
          env:
            - name: MONGO_CONN_STR
              value: mongodb://mongodb-svc:27017/prescripto?directConnection=true
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-sec
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-sec
                  key: password
          ports:
            - containerPort: 4000
          livenessProbe:
livenessProbe:
  httpGet:
    path: /ok
    port: 4000
  initialDelaySeconds: 30 # Give more time for application startup
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3 # Allow a few failures before taking action
readinessProbe:
  httpGet:
    path: /ok
    port: 4000
  initialDelaySeconds: 30 # Align with liveness probe
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
